version: '3'
networks:
  rabbit-network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbit-network